---
- name: test
- hosts: all
  vars:
    http_port: 80
    server_name: www.xxx.com
  remote_user: root
  gather_facts: false

  tasks:
  - name: 安装nginx最新版
    yum: pkg=nginx state=latest

  - name: 写入nginx配置文件
    template: src=nginx.conf dest=/etc/nginx/nginx.conf
    notify:
    - restart nginx
    
  - name: 确保nginx正在运行
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded